import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { scanSite, type ScanResult } from "@/lib/scanner";

export const dynamic = "force-dynamic";

function hex(h: string): [number, number, number] {
  const n = parseInt(h.replace("#", ""), 16);
  return [(n >> 16 & 255) / 255, (n >> 8 & 255) / 255, (n & 255) / 255];
}

async function buildPdf(result: ScanResult): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const regular = await doc.embedFont(StandardFonts.Helvetica);

  const W = 595, H = 842, M = 50;
  let page = doc.addPage([W, H]);
  let y = H - M;

  function text(str: string, x: number, yPos: number, size: number, font = regular, color: [number, number, number] = [0, 0, 0]) {
    page.drawText(str, { x, y: yPos, size, font, color: rgb(...color) });
  }

  function line(yPos: number) {
    page.drawLine({ start: { x: M, y: yPos }, end: { x: W - M, y: yPos }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
  }

  function checkPage(needed = 40) {
    if (y < M + needed) { page = doc.addPage([W, H]); y = H - M; }
  }

  // Header
  text("AI Agent Exposure Report", M, y, 22, bold);
  y -= 28;
  text(`Target: ${result.targetUrl}`, M, y, 10, regular, [0.4, 0.4, 0.4]);
  y -= 16;
  text(`Scanned: ${new Date(result.scannedAt).toUTCString()}`, M, y, 10, regular, [0.4, 0.4, 0.4]);
  y -= 24;
  line(y); y -= 20;

  // Score box
  const scoreColor: [number, number, number] = result.exposureScore > 60 ? hex("#8F2D56") : result.exposureScore > 30 ? hex("#F4A261") : hex("#0F766E");
  page.drawRectangle({ x: M, y: y - 80, width: 160, height: 90, color: rgb(0.06, 0.14, 0.11) });
  text("EXPOSURE SCORE", M + 10, y - 16, 8, bold, [0.8, 0.8, 0.8]);
  text(`${result.exposureScore}`, M + 10, y - 58, 40, bold, scoreColor);
  text("/100", M + 68, y - 48, 16, regular, [0.7, 0.7, 0.7]);
  text(result.grade, M + 10, y - 76, 9, bold, scoreColor);

  const summaryWords = result.summary.match(/.{1,70}(\s|$)/g) ?? [result.summary];
  let sy = y - 12;
  text("Summary", M + 175, sy, 11, bold);
  sy -= 16;
  for (const line of summaryWords) { text(line.trim(), M + 175, sy, 9, regular, [0.3, 0.3, 0.3]); sy -= 14; }

  y -= 110; line(y); y -= 20;

  // Findings
  text("Detailed Findings", M, y, 14, bold); y -= 22;

  for (const f of result.findings) {
    checkPage(55);
    const fColor: [number, number, number] = f.status === "present" ? hex("#0F766E") : f.status === "warning" ? hex("#c07010") : hex("#8F2D56");
    const bgColor: [number, number, number] = f.status === "present" ? [0.94, 0.98, 0.97] : f.status === "warning" ? [0.99, 0.96, 0.88] : [0.98, 0.93, 0.95];
    const rowH = f.recommendation ? 58 : 44;
    page.drawRectangle({ x: M, y: y - rowH + 6, width: W - 2 * M, height: rowH, color: rgb(...bgColor) });
    text(`${f.label}`, M + 8, y, 10, bold, fColor);
    text(`[${f.status.toUpperCase()}]  +${f.impact}`, W - M - 80, y, 8, bold, fColor);
    y -= 14;
    const detailLines = f.detail.match(/.{1,90}(\s|$)/g) ?? [f.detail];
    for (const dl of detailLines) { text(dl.trim(), M + 8, y, 8.5, regular, [0.2, 0.2, 0.2]); y -= 12; }
    if (f.recommendation) {
      const recLines = (`→ ${f.recommendation}`).match(/.{1,90}(\s|$)/g) ?? [f.recommendation];
      for (const rl of recLines) { text(rl.trim(), M + 8, y, 8, regular, [0.4, 0.4, 0.4]); y -= 12; }
    }
    y -= 10;
  }

  checkPage(80);
  line(y); y -= 20;

  // HTTP Headers
  text("HTTP Header Scan", M, y, 14, bold); y -= 22;
  for (const [k, v] of Object.entries(result.headers)) {
    checkPage(30);
    text(k, M, y, 9, bold, [0.2, 0.2, 0.2]);
    text(v || "Not detected", M + 180, y, 9, regular, v ? [0.1, 0.1, 0.1] : [0.6, 0.6, 0.6]);
    y -= 16;
  }

  // Footer on last page
  checkPage(20);
  y = M + 10;
  line(y); y -= 14;
  text("Generated by agentpolicy.vercel.app — AI Agent Policy Generator + Exposure Scanner", M, y, 7.5, regular, [0.6, 0.6, 0.6]);

  return doc.save();
}

export async function GET(request: NextRequest) {
  try {
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: "2026-02-25.clover" });
    const sessionId = request.nextUrl.searchParams.get("session_id");
    if (!sessionId) return NextResponse.json({ error: "session_id required." }, { status: 400 });

    const session = await stripe.checkout.sessions.retrieve(sessionId);
    if (session.payment_status !== "paid") return NextResponse.json({ error: "Payment not completed." }, { status: 402 });

    const targetUrl = session.metadata?.targetUrl;
    if (!targetUrl) return NextResponse.json({ error: "No target URL in session." }, { status: 400 });

    const result = await scanSite(targetUrl);
    const pdf = await buildPdf(result);

    return new NextResponse(pdf.buffer as ArrayBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="agentpolicy-report-${Date.now()}.pdf"`,
        "Content-Length": String(pdf.length),
      },
    });
  } catch (e) {
    console.error("report error:", e);
    return NextResponse.json({ error: e instanceof Error ? e.message : "Report generation failed." }, { status: 500 });
  }
}
