import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";
import PDFDocument from "pdfkit";
import { scanSite, type ScanResult } from "@/lib/scanner";

export const dynamic = "force-dynamic";

function buildPdf(result: ScanResult): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(24).font("Helvetica-Bold").text("AI Agent Exposure Report", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(12).font("Helvetica").fillColor("#666")
      .text(`Generated: ${new Date(result.scannedAt).toUTCString()}`, { align: "center" });
    doc.moveDown(0.3).text(`Target: ${result.targetUrl}`, { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(16).font("Helvetica-Bold").fillColor("#000").text("Exposure Score");
    doc.moveDown(0.3);
    const scoreColor = result.exposureScore > 60 ? "#8F2D56" : result.exposureScore > 30 ? "#F4A261" : "#0F766E";
    doc.fontSize(48).fillColor(scoreColor).text(`${result.exposureScore}/100`, { align: "center" });
    doc.fontSize(14).fillColor("#333").text(result.grade, { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor("#555").font("Helvetica").text(result.summary, { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(16).font("Helvetica-Bold").fillColor("#000").text("Detailed Findings");
    doc.moveDown(0.5);

    for (const f of result.findings) {
      const color = f.status === "present" ? "#0F766E" : f.status === "warning" ? "#F4A261" : "#8F2D56";
      doc.fontSize(12).font("Helvetica-Bold").fillColor(color).text(`${f.label}  [${f.status.toUpperCase()}]`);
      doc.fontSize(10).font("Helvetica").fillColor("#333").text(f.detail, { indent: 10 });
      if (f.recommendation) doc.fontSize(10).fillColor("#666").text(`→ ${f.recommendation}`, { indent: 10 });
      doc.moveDown(0.5);
    }

    doc.addPage();
    doc.fontSize(16).font("Helvetica-Bold").fillColor("#000").text("HTTP Header Scan");
    doc.moveDown(0.5);
    for (const [k, v] of Object.entries(result.headers)) {
      doc.fontSize(10).font("Helvetica-Bold").fillColor("#333").text(k, { continued: true });
      doc.font("Helvetica").fillColor("#555").text(`  ${v || "Not detected"}`);
    }

    doc.moveDown(1.5);
    doc.fontSize(9).fillColor("#999").font("Helvetica")
      .text("Generated by agentpolicy.vercel.app — AI Agent Policy Generator + Exposure Scanner", { align: "center" });
    doc.end();
  });
}

export async function GET(request: NextRequest) {
  try {
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, { apiVersion: "2026-02-25.clover" });
    const sessionId = request.nextUrl.searchParams.get("session_id");
    if (!sessionId) return NextResponse.json({ error: "session_id required." }, { status: 400 });

    const session = await stripe.checkout.sessions.retrieve(sessionId);
    if (session.payment_status !== "paid") return NextResponse.json({ error: "Payment not completed." }, { status: 402 });

    const targetUrl = session.metadata?.targetUrl;
    if (!targetUrl) return NextResponse.json({ error: "No target URL in session." }, { status: 400 });

    const result = await scanSite(targetUrl);
    const pdf = await buildPdf(result);

    return new NextResponse(pdf.buffer as ArrayBuffer, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="agentpolicy-report-${Date.now()}.pdf"`,
        "Content-Length": String(pdf.length),
      },
    });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Report generation failed." }, { status: 500 });
  }
}
